import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { mongoConnect } from "@/lib/database";
import Entries from './../models/Entries';

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  await mongoConnect();
  const entries = await Entries.find({});

  return (
    <html lang="en">
      <body className={inter.className}>
        <h1>Layout</h1>
        <div>
          {entries.map((entry: any) => (
            <p key={entry._id}>{entry.foo}</p>
          ))}
        </div>
        {children}
      </body>
    </html>
  );
}

