import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { cookies } from "next/headers";
import Link from "next/link";
import { createContext } from 'react';

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export const UserContext = createContext(undefined);

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const auth_token = cookies().get('auth_token')?.value ?? null;
  // todo: get current user (save in context)

  return (
    <html lang="en">
      <UserContext.Provider value={undefined}>
        <body className={inter.className}>
          <header>
            <nav>
              <ul>
                <li>
                  <Link href="/">Home</Link>
                </li>
                <li>
                  <Link href="/login">Login</Link>
                </li>
              </ul>
            </nav>
          </header>
          {children}
        </body>
      </UserContext.Provider>
    </html>
  );
}
